language: node_js
node_js:
  - "8.0.0"

branches:
  only:
    - master

before_script:
  - npm install -g yarn
  - npm install -g @angular/cli
  - yarn install
  - npm test --single-run --browsers PhantomJS
  - npm e2e

script:
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
