sudo: required
dist: trusty

language: node_js
node_js:
  - 6
  - 7
  - 8

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm install -g yarn

  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add @angular/cli

before_script:
  - yarn install

script:
  - npm run lint
  - ng build --prod
  - npm test
  - npm e2e

notifications:
  email:
    on_failure: change
    on_success: change
