language: node_js
node_js:
  - "8.0.0"
  - "6.10"
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - ng test
  - ng e2e

script:
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
